### ISSUE TITLE
Are there examples (code) of using Aneris?

### ISSUE THREAD

**Issue by l1yefeng** [logsem/aneris#3]
Hi creators of Aneris. I am interested in this project and would like to play with it. There are several examples mentioned in the paper such as the "Add" client-server protocol. Do you mind sharing the source code (aneris program, spec, and proof) of such examples?

Thank you.

**Comment by simongregersen** [comment]
The Coq development from the ESOP paper is available on [iris-project.org](https://iris-project.org/artifacts/2020-esop-aneris.tar.gz). There is also an artifact for our [POPL 2022 paper](https://zenodo.org/record/4066608). We are working on making all the developments available on GitHub (together with all the examples, newest version of the project, etc) very soon.

**Comment by l1yefeng** [comment]
Much appreciated.

**Comment by l1yefeng** [comment]
I am not very experienced with Iris and am studying it. If you don't mind, will you be so kind to show me how the calculator example (one server adding two ints) is proved with this GitHub version of Aneris? I notice that the esop examples are developed with an old version and I'm trying to redo it, but I'm having trouble proceeding.

**Comment by simongregersen** [comment]
The repository has now been updated and contains multiple example usages and case studies. For an introductory example, check out the `ping_pong` folder in `aneris/examples`. If you have other questions, you're welcome to send me an e-mail at gregersen@cs.au.dk.
